[www]
user  = www-data
group = www-data

listen = 9000

; Dynamic : s'adapte à la charge
pm                   = dynamic
pm.max_children      = 20
pm.start_servers     = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 8
; Recycler les workers après N requêtes (évite les memory leaks)
pm.max_requests      = 500

; Logs lents > 3s
slowlog              = /proc/self/fd/2
request_slowlog_timeout = 3s
